# -*- coding: utf-8 -*-
"""Нейромережі лр 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17RTGE0wd6fI8d_UyYWM3FTQ-dv-yFW4Z

<h1>Лабораторна робота №2<br>
ІП-33 Антюк Юлія</h1>

<h2>Реалізація та дослідження базових архітектур нейронних мереж для моделювання функцій двох змінних</h2>

Імпорт необхідних бібліотек
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, SimpleRNN, Input, Add
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

"""Для роботи обрано функцію y = 2x^2 + 0.7y^2. x, y є [0, 10]."""

def generate_data(n_samples=1000):
    X = np.random.uniform(0, 10, (n_samples, 2))
    Y = 2*X[:, 0]**2 + 0.7*X[:, 1]**2
    return X, Y

"""Функція нижче навчає модель на 200 епохах і виводить середню відносну помилку."""

def train_and_evaluate(model, X_train, Y_train, X_test, Y_test,
                       epochs=200, batch_size=16):

    model.compile(optimizer='adam', loss='mse')

    history = model.fit(
        X_train, Y_train,
        epochs=epochs,
        batch_size=batch_size,
        verbose=0,
        validation_data=(X_test, Y_test)
    )

    Y_pred = model.predict(X_test)
    error = np.mean(np.abs((Y_test - Y_pred.flatten()) / Y_test))

    r2 = r2_score(Y_test, Y_pred)

    return history, error, Y_pred, r2

"""Генерація даних та поділ на навчальну і тестову вибірки."""

X, Y = generate_data()

X_train, X_test = X[:800], X[800:]
Y_train, Y_test = Y[:800], Y[800:]

"""<h3>Побудова моделей<h3>

Feedforward backprop

1 внутрішній шар з 10 нейронами.
"""

ff_10 = Sequential([
    Input(shape=(2,)),
    Dense(10, activation='relu'),
    Dense(1)
])

"""1 внутрішній шар з 20 нейронами."""

ff_20 = Sequential([
    Input(shape=(2,)),
    Dense(20, activation='relu'),
    Dense(1)
])

"""Cascade forward backdrop

1 внутрішній шар з 20 нейронами.
"""

inputs = Input(shape=(2,))
hidden = Dense(20, activation='relu')(inputs)
output_main = Dense(1)(hidden)
output_skip = Dense(1)(inputs)
final_output = Add()([output_main, output_skip])

cascade_20 = Model(inputs=inputs, outputs=final_output)

"""2 внутрішніх шари по 10 нейронів у кожному."""

inputs2 = Input(shape=(2,))
h1 = Dense(10, activation='relu')(inputs2)
h2 = Dense(10, activation='relu')(h1)
out_main = Dense(1)(h2)
out_skip = Dense(1)(inputs2)
final_output2 = Add()([out_main, out_skip])

cascade_2x10 = Model(inputs=inputs2, outputs=final_output2)

"""Elman backprop

1 внутрішній шар з 15 нейронами.
"""

elman_15 = Sequential([
    SimpleRNN(15, activation='relu', input_shape=(2, 1)),
    Dense(1)
])

"""3 внутрішніх шари по 5 нейронів у кожному."""

elman_3x5 = Sequential([
    SimpleRNN(5, activation='relu', return_sequences=True, input_shape=(2,1)),
    SimpleRNN(5, activation='relu', return_sequences=True),
    SimpleRNN(5, activation='relu'),
    Dense(1)
])

"""<h3>Навчання моделей</h3>"""

models = {
    "FeedForward (10)": ff_10,
    "FeedForward (20)": ff_20,
    "Cascade (20)": cascade_20,
    "Cascade (2x10)": cascade_2x10,
    "Elman (15)": elman_15,
    "Elman (3x5)": elman_3x5
}

errors = {}
predictions = {}
r2_scores = {}

plt.figure(figsize=(10,6))

for name, model in models.items():
    print(f"Навчання {name}...")

    if "Elman" in name:
        X_train_rnn = X_train.reshape((X_train.shape[0], 2, 1))
        X_test_rnn = X_test.reshape((X_test.shape[0], 2, 1))

        history, error, Y_pred, r2 = train_and_evaluate(
            model, X_train_rnn, Y_train, X_test_rnn, Y_test
        )
    else:
        history, error, Y_pred, r2 = train_and_evaluate(
            model, X_train, Y_train, X_test, Y_test
        )

    errors[name] = error
    predictions[name] = Y_pred
    r2_scores[name] = r2

    plt.plot(history.history['loss'], label=name)

plt.title("Зміна MSE під час навчання")
plt.xlabel("Епохи")
plt.ylabel("MSE")
plt.legend()
plt.show()

for name, error in errors.items():
    print(f"{name}: MRE = {error:.4f}, R² = {r2_scores[name]:.4f}")

"""Подивимось на вигляд справжньої функції і її апроксимацію."""

from mpl_toolkits.mplot3d import Axes3D

x = np.linspace(0, 10, 50)
y = np.linspace(0, 10, 50)
X_grid, Y_grid = np.meshgrid(x, y)

Z_true = 2*X_grid**2 + 0.7*Y_grid**2

grid_points = np.c_[X_grid.ravel(), Y_grid.ravel()]

for name, model in models.items():
    if "Elman" in name:
        grid_input = grid_points.reshape((grid_points.shape[0], 2, 1))
    else:
        grid_input = grid_points

    Z_pred = model.predict(grid_input)
    Z_pred = Z_pred.reshape(X_grid.shape)

    fig = plt.figure(figsize=(30,6))
    ax1 = fig.add_subplot(121, projection='3d')
    ax1.plot_surface(X_grid, Y_grid, Z_true, cmap='viridis')
    ax1.set_title("Actual Function")
    ax1.set_xlabel('X')
    ax1.set_ylabel('Y')
    ax1.set_zlabel('f(x,y)')

    ax2 = fig.add_subplot(111, projection='3d')
    ax2.plot_surface(X_grid, Y_grid, Z_pred, cmap='viridis')

    ax2.set_title(f'Prediction surface: {name}')
    ax2.set_xlabel('X')
    ax2.set_ylabel('Y')
    ax2.set_zlabel('f(x,y)')

    plt.show()