# -*- coding: utf-8 -*-
"""Нейромережі лр 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IiamIB8-6j_95ri8TC-Ixp_JoA7qRu-

<h1>Лабораторна робота №3<br>
ІП-33 Антюк Юлія</h1>

<h2>Реалізація нейронної мережі прямого розповсюдження для розпізнавання зображення</h2>

Імпорт необхідних бібліотек.
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

"""Завантажуємо датасет."""

(x_train, y_train), (x_test, y_test) = mnist.load_data()

"""Масштабування пікселів від 0-255 до 0-1."""

x_train = x_train.reshape(-1, 28*28) / 255.0
x_test = x_test.reshape(-1, 28*28) / 255.0

"""One-hot encoding для міток класів."""

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

"""Побудова моделі:
- вхідний шар 28*28 нейронів;
- перший прихований шар 256 нейронів;
- другий прихований шар 128 нейронів;
- третій прихований шар 64 нейрони;
- вихідний шар 10 нейронів (10 класів).
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential([
    Dense(256, activation='relu', input_shape=(28*28,)),
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

"""Компіляція та навчання мережі."""

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=32,
                    validation_split=0.1)

"""Побудуємо графік залежності loss і accuracy від епохи, використовуючи об'єкт history."""

loss = history.history['loss']
val_loss = history.history['val_loss']
accuracy = history.history['accuracy']
val_accuracy = history.history['val_accuracy']
epochs = range(1, len(loss)+1)

# Графік loss
plt.figure(figsize=(12,5))

plt.subplot(1, 2, 1)
plt.plot(epochs, loss, 'b-o', label='Train Loss')
plt.plot(epochs, val_loss, 'r-o', label='Validation Loss')
plt.title('Залежність Loss від епохи')
plt.xlabel('Епоха')
plt.ylabel('Loss')
plt.legend()

# Графік accuracy
plt.subplot(1, 2, 2)
plt.plot(epochs, accuracy, 'b-o', label='Train Accuracy')
plt.plot(epochs, val_accuracy, 'r-o', label='Validation Accuracy')
plt.title('Залежність Accuracy від епохи')
plt.xlabel('Епоха')
plt.ylabel('Accuracy')
plt.legend()

plt.show()

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Матриця помилок
cm = confusion_matrix(y_true, y_pred_classes)

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=True)
plt.title("Матриця помилок (Confusion Matrix)")
plt.xlabel("Передбачений клас")
plt.ylabel("Справжній клас")
plt.show()

# Метрики precision, recall, F1-score
report = classification_report(y_true, y_pred_classes)
print("Класифікаційний звіт:\n", report)

"""З матриці помилок видно, що всі класи розпізнаються дуже добре. Найбільше плутається 5 і 3, 9 і 4, що досить логічно. Класифікаційний звіт показав високе значення accuracy, precision, recall та f1-score.

Напишемо функцію для тестування власноруч написаних цифр. Функція приймає файл у форматі .png як параметр, конвертує у відтінки сірого, інвертує зображення, якщо фон білий і використовує створену модель для розпізнавання чисел.
"""

from PIL import Image
import matplotlib.pyplot as plt

def predict_digit(image_path):
    img = Image.open(image_path).convert('L')  # конвертація у відтінки сірого
    img = img.resize((28, 28))
    img_array = np.array(img)
    img_array = 255 - img_array               # інвертування, якщо фон білий
    img_array = img_array.reshape(1, 28*28) / 255.0

    prediction = model.predict(img_array)
    digit = np.argmax(prediction)

    plt.imshow(img_array.reshape(28,28), cmap='gray')
    plt.title(f'Predicted: {digit}')
    plt.show()

    return digit

import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

path = '/content/drive/MyDrive/6 семестр/Нейромережі/Numbers/'

for i in range(10):
    file_name = f"{path}num_{i}.png"
    predict_digit(file_name)

"""Після тестування бачимо, що модель помилилася лише в одному випадку - на цифрі 9."""